# Generated by Django 5.0.1 on 2024-04-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField(null=True)),
                ('place', models.TextField(max_length=250)),
                ('job', models.TextField(max_length=250)),
                ('education', models.TextField(max_length=250)),
                ('number', models.IntegerField()),
                ('email', models.TextField(null=True)),
                ('facebook_id', models.CharField(max_length=250)),
                ('instagra_id', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('car_or_two_wheel_number', models.CharField(max_length=250)),
            ],
        ),
    ]
