# Generated by Django 5.0.1 on 2024-04-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_rename_instagra_id_data_instagrm_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='facebook_id',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='instagrm_id',
            new_name='instagrm',
        ),
    ]
