# Generated by Django 5.0.1 on 2024-04-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_remove_data_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='instagrm',
        ),
    ]
