# Generated by Django 5.0.1 on 2024-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_data_instagrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='facebook',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='instagrm',
            field=models.TextField(null=True),
        ),
    ]
