# Generated by Django 5.0.1 on 2024-04-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_data_facebook_data_instagrm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='instagrm',
            new_name='instagram',
        ),
    ]
